"""Ground-truth questions for "2022 Q3 AAPL.pdf" (Apple 10-Q, quarter ended June 25, 2022).

A retrieved chunk is *relevant* to a case if its content contains every string in
`evidence`. Evidence strings are figures copied verbatim from the PDF, so the check
is independent of which page or chunk type (text/table) the fact landed in.

`answer` is the value a correct generated answer must mention (used by the live test).
"""

DEV_SET = [
    {
        "id": "net_sales_q3",
        "question": "What were Apple's total net sales in the third quarter of 2022?",
        "evidence": ["82,959"],
        "answer": "82,959",
    },
    {
        "id": "net_sales_9m",
        "question": "What were total net sales for the nine months ended June 25, 2022?",
        "evidence": ["304,182"],
        "answer": "304,182",
    },
    {
        "id": "iphone_sales_q3",
        "question": "How much iPhone net sales did Apple report in Q3 2022?",
        "evidence": ["iPhone", "40,665"],
        "answer": "40,665",
    },
    {
        "id": "net_income_q3",
        "question": "What was Apple's net income for the quarter ended June 25, 2022?",
        "evidence": ["Net income", "19,442"],
        "answer": "19,442",
    },
    {
        "id": "diluted_eps_9m",
        "question": "What were diluted earnings per share for the nine months ended June 25, 2022?",
        "evidence": ["Diluted", "4.82"],
        "answer": "4.82",
    },
    {
        "id": "shares_outstanding",
        "question": "How many shares of common stock were issued and outstanding as of July 15, 2022?",
        "evidence": ["16,070,752,000"],
        "answer": "16,070,752,000",
    },
    {
        "id": "cash_equivalents",
        "question": "What was the balance of cash and cash equivalents on the balance sheet?",
        "evidence": ["Cash and cash equivalents", "27,502"],
        "answer": "27,502",
    },
    {
        "id": "noncurrent_term_debt",
        "question": "What was the non-current term debt on the balance sheet at June 25, 2022?",
        "evidence": ["Term debt", "94,700"],
        "answer": "94,700",
    },
    {
        "id": "rnd_q3",
        "question": "How much did Apple spend on research and development in the third quarter?",
        "evidence": ["Research and development", "6,797"],
        "answer": "6,797",
    },
    {
        "id": "services_gross_margin",
        "question": "What was the services gross margin for the third quarter of 2022?",
        "evidence": ["Services", "14,015"],
        "answer": "14,015",
    },
    {
        "id": "buyback_q3",
        "question": "How much common stock did the Company repurchase during the third quarter?",
        "evidence": ["repurchased $21.7 billion"],
        "answer": "21.7 billion",
    },
    {
        "id": "shares_repurchased_9m",
        "question": "How many shares did Apple repurchase in the first nine months of 2022 and for how much?",
        "evidence": ["repurchased 408 million shares"],
        "answer": "408 million",
    },
    {
        "id": "quarterly_dividend",
        "question": "What is the quarterly cash dividend per share?",
        "evidence": ["quarterly cash dividend was $0.23"],
        "answer": "0.23",
    },
    {
        "id": "net_sales_growth_driver",
        "question": "What drove the increase in total net sales during the third quarter of 2022?",
        "evidence": ["Total net sales increased 2%"],
        "answer": "2%",
    },
]

# Written AFTER the retrieval fixes were designed against DEV_SET, from other parts of the
# filing. Use it to check that gains generalise; don't tune retrieval against it.
HELDOUT_SET = [
    {
        "id": "operating_income_q3",
        "question": "What was Apple's operating income in the third quarter of 2022?",
        "evidence": ["Operating income", "23,076"],
        "answer": "23,076",
    },
    {
        "id": "total_assets",
        "question": "What were Apple's total assets as of June 25, 2022?",
        "evidence": ["Total assets", "336,309"],
        "answer": "336,309",
    },
    {
        "id": "total_liabilities",
        "question": "What were total liabilities on the balance sheet?",
        "evidence": ["Total liabilities", "278,202"],
        "answer": "278,202",
    },
    {
        "id": "sga_q3",
        "question": "How much did the company spend on selling, general and administrative in Q3?",
        "evidence": ["Selling, general and administrative", "6,012"],
        "answer": "6,012",
    },
    {
        "id": "tax_provision_q3",
        "question": "What was the provision for income taxes for the three months ended June 25, 2022?",
        "evidence": ["Provision for income taxes", "3,624"],
        "answer": "3,624",
    },
    {
        "id": "operating_cash_flow_9m",
        "question": "How much cash was generated by operating activities in the first nine months of 2022?",
        "evidence": ["Cash generated by operating activities", "98,024"],
        "answer": "98,024",
    },
    {
        "id": "commercial_paper",
        "question": "How much commercial paper was outstanding?",
        "evidence": ["Commercial paper", "10,982"],
        "answer": "10,982",
    },
    {
        "id": "mac_sales_q3",
        "question": "What were Mac net sales in the third quarter of 2022?",
        "evidence": ["Mac", "7,382"],
        "answer": "7,382",
    },
    {
        "id": "inventories",
        "question": "What was the inventories balance at June 25, 2022?",
        "evidence": ["Inventories", "5,433"],
        "answer": "5,433",
    },
    {
        "id": "gross_margin_total_q3",
        "question": "What was the total gross margin in the third quarter of 2022?",
        "evidence": ["Total gross margin", "35,885"],
        "answer": "35,885",
    },
    {
        "id": "depreciation_9m",
        "question": "How much depreciation and amortization was recorded in the nine months ended June 25, 2022?",
        "evidence": ["Depreciation and amortization", "8,239"],
        "answer": "8,239",
    },
    {
        "id": "effective_tax_rate_trend",
        "question": "How did the effective tax rate for the third quarter of 2022 compare with the prior year?",
        "evidence": ["effective tax rate for the third quarter of 2022 was higher"],
        "answer": "higher",
    },
]

from tests.golden_set_extra import EXTRA_SET  # noqa: E402  (written by a separate pass; never tuned on)

GOLDEN_SET = (
    [{**c, "split": "dev"} for c in DEV_SET]
    + [{**c, "split": "heldout"} for c in HELDOUT_SET]
    + [{**c, "split": "extra"} for c in EXTRA_SET]
)
